### ISSUE TITLE
匹 配 后 拉 黑

### ISSUE THREAD

**Issue by ESWZY** [MeetinaXD/CleanBilibiliComment#1]
提feature狂魔来了

能否可以在匹配之后提取用户uid，然后用这个api拉黑🌚

https://github.com/Hsury/Bilibili-Toolkit/blob/411307217b07ad37485e9642aab8761b4cc50eda/bilibili.py#L676-L690

这样就治根了

（虽然现在环境比以前好点了🌚

**Comment by MeetinaXD** [comment]
感谢你提issue，自动拉黑功能已经添加到最新的一个commit中。

此处使用了上面的api
https://github.com/MeetinaXD/CleanBilibiliComment/blob/cf9100946ddb57ccdbf221c0fb5f62ae6d648446/clean-bilibili-comment.js#L49-L80

隔了一年才看到，真是抱歉

**Comment by ESWZY** [comment]
好耶
